name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # This runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-22.04  # Use Ubuntu 24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Disable ImageMagick (Fix for X11 error)
        run: |
          sudo apt-get remove --purge imagemagick
          sudo apt-get autoremove -y

      - name: Fetch repositories and update README (Python Script)
        run: |
          echo 'import requests' > update_readme.py
          echo '' >> update_readme.py
          echo '# GitHub API request' >> update_readme.py
          echo "username = 'imvjai'" >> update_readme.py
          echo "url = f'https://api.github.com/users/{username}/repos?per_page=100'" >> update_readme.py
          echo 'response = requests.get(url)' >> update_readme.py
          echo 'repos = response.json()' >> update_readme.py
          echo '' >> update_readme.py
          echo '# Initialize the markdown table' >> update_readme.py
          echo 'table = "| Repository Name | Description | Scripts/Automation |\\n"' >> update_readme.py
          echo 'table += "|-----------------|-------------|--------------------|\\n"' >> update_readme.py
          echo '' >> update_readme.py
          echo '# Exclude the \'imvijay\' repository' >> update_readme.py
          echo 'for repo in repos:' >> update_readme.py
          echo '    if repo["name"] == "imvijay":' >> update_readme.py
          echo '        continue' >> update_readme.py
          echo '' >> update_readme.py
          echo '    # Fetch repository contents' >> update_readme.py
          echo '    repo_url = f"https://api.github.com/repos/{username}/{repo["name"]}/contents"' >> update_readme.py
          echo '    repo_contents = requests.get(repo_url).json()' >> update_readme.py
          echo '' >> update_readme.py
          echo '    # Check if any folder contains a README.md' >> update_readme.py
          echo '    readme_content = ""' >> update_readme.py
          echo '    for file in repo_contents:' >> update_readme.py
          echo '        if file["name"] == "README.md":' >> update_readme.py
          echo '            file_content = requests.get(file["download_url"]).text' >> update_readme.py
          echo '            readme_content = file_content.splitlines()[0]  # Get the first line as snippet' >> update_readme.py
          echo '            break' >> update_readme.py
          echo '' >> update_readme.py
          echo '    # Add the repository info to the table' >> update_readme.py
          echo '    table += f"| [{repo["name"]}]({repo["html_url"]}) | {repo.get("description", "No description")} | {readme_content} |\\n"' >> update_readme.py
          echo '' >> update_readme.py
          echo '# Read the current README file' >> update_readme.py
          echo 'with open("README.md", "r") as file:' >> update_readme.py
          echo '    readme_content = file.read()' >> update_readme.py
          echo '' >> update_readme.py
          echo '# Append the table to the README' >> update_readme.py
          echo 'readme_content += "\\n## 🚀 Repositories List\\n" + table' >> update_readme.py
          echo '' >> update_readme.py
          echo '# Write the updated README' >> update_readme.py
          echo 'with open("README.md", "w") as file:' >> update_readme.py
          echo '    file.write(readme_content)' >> update_readme.py

          python update_readme.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions Bot'
          author_email: 'actions@github.com'
          message: 'Auto-update repository list in README'
