name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # This runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch repositories and update README
        run: |
          import requests
          import os

          # GitHub API request
          username = "imvjai"
          url = f"https://api.github.com/users/{username}/repos?per_page=100"
          response = requests.get(url)
          repos = response.json()

          # Initialize the markdown table
          table = "| Repository Name | Description | Scripts/Automation |\n"
          table += "|-----------------|-------------|--------------------|\n"

          # Exclude the 'imvijay' repository
          for repo in repos:
              if repo['name'] == 'imvijay':
                  continue

              # Fetch repository contents
              repo_url = f"https://api.github.com/repos/{username}/{repo['name']}/contents"
              repo_contents = requests.get(repo_url).json()

              # Check if any folder contains a README.md
              readme_content = ""
              for file in repo_contents:
                  if file['name'] == 'README.md':
                      file_content = requests.get(file['download_url']).text
                      readme_content = file_content.splitlines()[0]  # Get the first line as snippet
                      break

              # Add the repository info to the table
              table += f"| [{repo['name']}]({repo['html_url']}) | {repo.get('description', 'No description')} | {readme_content} |\n"

          # Read the current README file
          with open("README.md", "r") as file:
              readme_content = file.read()

          # Append the table to the README
          readme_content += "\n## 🚀 Repositories List\n" + table

          # Write the updated README
          with open("README.md", "w") as file:
              file.write(readme_content)

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions Bot'
          author_email: 'actions@github.com'
          message: 'Auto-update repository list in README'
